/*
Program to verify The Birthday Paradox.
Dynamic test cases 
*/
#include<iostream>
#include<cstdio>
#include<stdlib.h>
using namespace std;

class Birthday
{
public:
	void accept();
	void  probability(int);
	void dynamic(int,int);	 
}; 

void Birthday::probability(int person)
{
	int i;
    double p = 1;

    for(i = 1; i < person; i++)
     {
         p = p*((365.0-i)/365.0);  //calculating the probability of n number of person with the probability formula.
     }

     printf("\nThe probablity for the birthday is :: %f",1-p);

 
}
void Birthday::dynamic(int person,int tests)
{
    int birthdays[365] = {0};  //birthdays will have 365 elements, each corresponding to 1 day. (all initialized to 0)
    double p;
    int i,j,k,flag;
    double count=0;

    for(j = 0; j < tests; j++)
    {
        flag=0;

        for(i = 0; i < tests; i++)
            birthdays[i] = 0;          //initializing birthdays to 0 for each test case

        for(i = 0; i < person; i++)
            birthdays[rand()%365] += 1;  //for each birth date generated by rand, (out of 365),
                                        //its corresponding element in birthdays will be incremented by 1 (birthdays array is initialized to 0).
        for(i = 0; i < tests; i++)        //changed.
            if(birthdays[i] >= 2)       //two or more people have same birthdays
                    flag=1;             //i.e. mapped to the same element in birthdays array.

        if(flag==1)
            count++;
    }
    p=count/tests;
    printf("\nThe number of sets out of %d which have clashing birthdays :: %f\n",tests,count);
    printf("\nThe probability of persons with matching(pairs) birthday out of %d are :: %f\n",tests,p);
}

int main()
{
    Birthday b;
    int person;
    int tests;
    printf("Enter the number of people of whose you want to see the probability :: ");
    scanf("%d",&person);

    printf("Enter how many test you want to perform for getting the probability :: ");
    scanf("%d",&tests);
    
    b.probability(person); 
    b.dynamic(person,tests);

    return 0;
}
